version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: btc_nginx
    command: nginx -g "daemon off;"
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  php:
    build: docker/php
    container_name: btc_fpm
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    working_dir: /var/www/html/
